#!/bin/bash

# Making the script more robust
set -e # Exit on errors
set -u # Exit on uninitialized variables

RAILS_VERSION=${RAILS_VERSION:-}
if [ "$RAILS_VERSION" == "" ]; then
  echo "Please specify rails version using RAILS_VERSION environment variable!"
  exit 1
fi

cd test-project

# Print version info
echo "-----------------------------------------------------------------------------------------------------------------"
echo " * Running specs for Rails version $RAILS_VERSION..."
echo " * Ruby version: `ruby --version`"
echo " * Rubygems version: `gem --version`"
echo " * DbCharmer gem version: '${DB_CHARMER_GEM:-trunk}'"
echo "-----------------------------------------------------------------------------------------------------------------"

# Test environment
export RAILS_ENV=test

# Configure database access
cp -f config/database.yml.example config/database.yml

# Create databases and sharding tables
mysql -u root < db/create_databases.sql
mysql -u root db_charmer_sandbox_test < db/sharding.sql

# Install gems
rm -f Gemfile.lock
bundle install

# Run migrations
bundle exec rake --trace db:migrate

# Run the build and return its exit code
exec bundle exec rspec spec
