source 'http://rubygems.org'

gem 'rails', '2.3.11'

gem 'rake', '0.9.2.2'
gem 'mysql'

gem 'rspec', '1.3.2'
gem 'rspec-rails', '1.3.4'

# Load DbCharmer as a gem
gem 'db-charmer', :path => '..', :require => 'db_charmer'
