source 'http://rubygems.org'

gem 'rake', "0.9.2.2"
gem 'mysql', "2.8.1"

gem 'rspec', '< 3.0'
gem 'rspec-core', '< 3.0'
gem 'rspec-rails', '< 3.0'

# Load DbCharmer as a gem
if ENV['DB_CHARMER_GEM'].to_s == ''
  gem_path = File.expand_path(File.dirname(File.dirname(__FILE__)))
  puts "Using on-disk db-charmer code from '#{gem_path}'..."
  gem 'db-charmer', :path => gem_path, :require => 'db_charmer'
else
  puts "Using db-charmer gem: #{ENV['DB_CHARMER_GEM']}..."
  gem 'db-charmer', ENV['DB_CHARMER_GEM'], :require => 'db_charmer'
end

# Detect Rails version we need to use
rails_version_file = File.expand_path("../.rails-version", __FILE__)
version = File.exists?(rails_version_file) && File.read(rails_version_file).chomp
version ||= ENV['RAILS_VERSION']
version ||= '3-2-stable'

# Require gems for selected rails version
case version
when /master/
  gem "rails", :git => "git://github.com/rails/rails.git"
  gem "arel", :git => "git://github.com/rails/arel.git"
  gem "journey", :git => "git://github.com/rails/journey.git"
when /3-0-stable/
  gem "rails", :git => "git://github.com/rails/rails.git", :branch => "3-0-stable"
  gem "arel",  :git => "git://github.com/rails/arel.git", :branch => "2-0-stable"
when /3-1-stable/
  gem "rails", :git => "git://github.com/rails/rails.git", :branch => "3-1-stable"
when /3-2-stable/
  gem "rails", :git => "git://github.com/rails/rails.git", :branch => "3-2-stable"
else
  gem "rails", version
end
